### ISSUE TITLE
Exclude logs

### ISSUE THREAD

**Issue by DanielSmith1239** [urakozz/firebase-functions-auth#1]
Is there a way to use the library so that it doesn't print to the log whenever it authenticates a user?

**Comment by DanielSmith1239** [comment]
Never mind, I'm dumb. Just had to set enableLogs to false in the config.

**Comment by urakozz** [comment]
@DanielSmith1239 actually it’s  a valid point! I believe I better update readme too. I actually surprised and flattered somebody run into the same problem and found this small library useful 😊
